language: 'python'
python: '2.7'
sudo: false

env:
  - TOXENV=py27-ansible13
  - TOXENV=py27-ansible14
  - TOXENV=py27-ansible15
  - TOXENV=py27-ansible16
  - TOXENV=py27-ansible17
  - TOXENV=py27-ansible18
  - TOXENV=py27-ansible19

install:
  - 'pip install tox coveralls'
  - 'cp .travis/ansible.cfg ~/.ansible.cfg'
script:
  - 'tox -- -rs'
  - 'coveralls'
